title: "CS1400-Simulation-Project"
description: "Final Project for Computer Organization Course"
url: "https://badrchoubai.github.io"
author: "Badr Choubai"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
